#############################################################################
# Makefile for building: cloakcoin-qt
# Generated by qmake (8.0) (Qt 5.5.1)
# Project:  AI  ROBOT SYSTEM V80.pro
# Template: app
# Command: C:\Qt\5.5.1\bin\qmake.exe -spec win32-g++ "USE_QRCODE=1" "USE_UPNP=1" "USE_IPV6=1" -o Makefile cloakcoin-qt.pro
#############################################################################

MAKEFILE      = Makefile